### ISSUE TITLE
The wasm lib does not want to complile with opt 

### ISSUE THREAD

**Issue by arunavo4** [refilelabs/image#2]
The project compiles the wasm bundle only if I add this to my cargo.toml

```.toml
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
```

Other wise it throws an error about adding --enable-bulk-memory

```bash
[INFO]: ⬇️  Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[wasm-validator error in function convertImage\20externref\20shim] unexpected false: table.fill requires bulk-memory [--enable-bulk-memory], on 
(table.fill $1
 (local.get $8)
 (ref.null noextern)
 (i32.const 2)
)
[wasm-validator error in function loadMetadata\20externref\20shim] unexpected false: table.fill requires bulk-memory [--enable-bulk-memory], on 
(table.fill $1
 (local.get $5)
 (ref.null noextern)
 (i32.const 2)
)
Fatal: error validating input
Error: failed to execute `wasm-opt`: exited with exit status: 1
```

**Comment by tomvoet** [comment]
Thanks for pointing this out - it works on my machine (lol). 
I'll take a look at it, I've noticed similar behaviour on another machine of mine.
When I find something I'll let you know :)

**Comment by arunavo4** [comment]
Also I think you have nightly turned on can you switch to stable and a few more issues seem to pop up

**Comment by tomvoet** [comment]
Yeah you're right, also noticed that on my other machine haha :)
I fixed most of the things and will create a PR (hopefully) later today, as soon as I have a couple minutes to spare.
